name: Deploy VITE site to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (with legacy peer deps)
        run: npm install --legacy-peer-deps

      - name: Check if all required VITE secrets are available
        run: |
          if [ -z "${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}" ] || \
             [ -z "${{ secrets.VITE_EMAILJS_SERVICE_ID }}" ] || \
             [ -z "${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}" ] || \
             [ -z "${{ secrets.VITE_TOEMAIL }}" ]; then
            echo "One or more VITE secrets are not set. Cancelling the workflow."
            exit 1
          fi

      - name: Echo environment variables to .env
        run: |
          echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}" >> .env
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }}" >> .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_TOEMAIL=${{ secrets.VITE_TOEMAIL }}" >> .env

      - name: Build the VITE app
        run: npm run build

      - name: Create 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4